### ISSUE TITLE
Are you going to open source your code?

### ISSUE THREAD

**Issue by Lr-2002** [recall2imagine/recall2imagine.github.io#1]
Hello, @mrsamsami ,Thanks for your great work ,It's very insterested Especially the memory part ,It could solve lot of long-term memory task ! Congratulation again.
What's more I see that R2I's github page has show the code link to your repo ,While I cannot attend to it right now. Did you forget to change it to public repo or It'll be released future?

**Comment by artemZholus** [comment]
Hi @Lr-2002 , we are finishing the code currently and expect to open it in a few days. Please stay tuned for the updates at https://github.com/chandar-lab
